#pragma checksum "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\Pages\Counter.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9ab31720a87ee6549c994547abda91def9906b1f23bb1b8592b5be06681473f3"
// <auto-generated/>
#pragma warning disable 1591
namespace BlazorDSL.Components.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(2,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(3,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(4,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(5,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(6,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(7,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(8,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(9,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(10,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using BlazorDSL

#nullable disable
    ;
#nullable restore
#line (10,2)-(11,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\_Imports.razor"
using BlazorDSL.Components

#line default
#line hidden
#nullable disable
    ;
    [global::Microsoft.AspNetCore.Components.RouteAttribute(
    // language=Route,Component
#nullable restore
#line (1,7)-(1,17) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\Pages\Counter.razor"
"/counter"

#line default
#line hidden
#nullable disable
    )]
    #nullable restore
    public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h1>Counter</h1>\r\n\r\n");
            __builder.OpenElement(1, "div");
            __builder.AddAttribute(2, "class", "box");
            __builder.OpenElement(3, "p");
            __builder.AddContent(4, "Current count: ");
            __builder.AddContent(5, 
#nullable restore
#line (6,24)-(6,36) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\Pages\Counter.razor"
currentCount

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(6, "\r\n    ");
            __builder.OpenElement(7, "button");
            __builder.AddAttribute(8, "class", "btn btn-primary");
            __builder.AddAttribute(9, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (7,47)-(7,61) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\Pages\Counter.razor"
IncrementCount

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(10, "Click me");
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line (10,8)-(17,1) "C:\Users\alexanderboehm\Documents\Masterarbeit\Masterabeit-Ausarbeitung-DSL\BlazorDSL\Components\Pages\Counter.razor"

    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
